#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MpcRemoteDroid.Resource", IsApplication=true)]

namespace MpcRemoteDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::MpcRemoteDroid.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::MpcRemoteDroid.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::MpcRemoteDroid.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::MpcRemoteDroid.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::MpcRemoteDroid.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::MpcRemoteDroid.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::MpcRemoteDroid.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::MpcRemoteDroid.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::MpcRemoteDroid.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::MpcRemoteDroid.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::MpcRemoteDroid.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::MpcRemoteDroid.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::MpcRemoteDroid.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::MpcRemoteDroid.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::MpcRemoteDroid.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::MpcRemoteDroid.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::MpcRemoteDroid.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::MpcRemoteDroid.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::MpcRemoteDroid.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::MpcRemoteDroid.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::MpcRemoteDroid.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::MpcRemoteDroid.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::MpcRemoteDroid.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::MpcRemoteDroid.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::MpcRemoteDroid.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::MpcRemoteDroid.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::MpcRemoteDroid.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::MpcRemoteDroid.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::MpcRemoteDroid.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::MpcRemoteDroid.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::MpcRemoteDroid.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::MpcRemoteDroid.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::MpcRemoteDroid.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::MpcRemoteDroid.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::MpcRemoteDroid.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::MpcRemoteDroid.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::MpcRemoteDroid.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::MpcRemoteDroid.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::MpcRemoteDroid.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::MpcRemoteDroid.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::MpcRemoteDroid.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::MpcRemoteDroid.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::MpcRemoteDroid.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::MpcRemoteDroid.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::MpcRemoteDroid.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::MpcRemoteDroid.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::MpcRemoteDroid.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::MpcRemoteDroid.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::MpcRemoteDroid.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::MpcRemoteDroid.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::MpcRemoteDroid.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::MpcRemoteDroid.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::MpcRemoteDroid.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::MpcRemoteDroid.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::MpcRemoteDroid.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::MpcRemoteDroid.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::MpcRemoteDroid.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_install_form_unknown_sources_disabled = global::MpcRemoteDroid.Resource.String.hockeyapp_error_install_form_unknown_sources_disabled;
			global::HockeyApp.Resource.String.hockeyapp_error_no_external_storage_permission = global::MpcRemoteDroid.Resource.String.hockeyapp_error_no_external_storage_permission;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::MpcRemoteDroid.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::MpcRemoteDroid.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::MpcRemoteDroid.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_added = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_attachment_added;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_remove_description = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_attachment_remove_description;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_removed = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_attachment_removed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint_required = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_email_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint_required = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_message_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint_required = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_name_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_new_answer_notification_message = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_new_answer_notification_message;
			global::HockeyApp.Resource.String.hockeyapp_feedback_notification_channel = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_notification_channel;
			global::HockeyApp.Resource.String.hockeyapp_feedback_notification_title = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_notification_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_screenshot_fail = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_screenshot_fail;
			global::HockeyApp.Resource.String.hockeyapp_feedback_screenshot_notification_message = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_screenshot_notification_message;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sent_toast = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_sent_toast;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint_required = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_subject_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::MpcRemoteDroid.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint_required = global::MpcRemoteDroid.Resource.String.hockeyapp_login_email_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::MpcRemoteDroid.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::MpcRemoteDroid.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::MpcRemoteDroid.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::MpcRemoteDroid.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint_required = global::MpcRemoteDroid.Resource.String.hockeyapp_login_password_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::MpcRemoteDroid.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::MpcRemoteDroid.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::MpcRemoteDroid.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::MpcRemoteDroid.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::MpcRemoteDroid.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::MpcRemoteDroid.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::MpcRemoteDroid.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::MpcRemoteDroid.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_update_already_installed = global::MpcRemoteDroid.Resource.String.hockeyapp_update_already_installed;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::MpcRemoteDroid.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::MpcRemoteDroid.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::MpcRemoteDroid.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::MpcRemoteDroid.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::MpcRemoteDroid.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_loading = global::MpcRemoteDroid.Resource.String.hockeyapp_update_loading;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::MpcRemoteDroid.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_newest_version = global::MpcRemoteDroid.Resource.String.hockeyapp_update_newest_version;
			global::HockeyApp.Resource.String.hockeyapp_update_no_info = global::MpcRemoteDroid.Resource.String.hockeyapp_update_no_info;
			global::HockeyApp.Resource.String.hockeyapp_update_restore = global::MpcRemoteDroid.Resource.String.hockeyapp_update_restore;
			global::HockeyApp.Resource.String.hockeyapp_update_title = global::MpcRemoteDroid.Resource.String.hockeyapp_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_unknown_size = global::MpcRemoteDroid.Resource.String.hockeyapp_update_unknown_size;
			global::HockeyApp.Resource.String.hockeyapp_update_version = global::MpcRemoteDroid.Resource.String.hockeyapp_update_version;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::MpcRemoteDroid.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::MpcRemoteDroid.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::MpcRemoteDroid.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::MpcRemoteDroid.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::MpcRemoteDroid.Resource.Style.HockeyApp_SingleLineInputStyle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int hockeyapp_background_header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hockeyapp_background_light = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int hockeyapp_background_white = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int hockeyapp_button_background = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int hockeyapp_button_background_pressed = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int hockeyapp_button_background_selected = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int hockeyapp_text_black = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int hockeyapp_text_light = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int hockeyapp_text_normal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int hockeyapp_text_white = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hockeyapp_btn_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_settings_remote_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_settings_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int preview = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090002
			public const int about_imageview = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int about_rights = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int about_title = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int about_version = 2131296257;
			
			// aapt resource value: 0x7f090011
			public const int button_add_response = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int button_attachment = 2131296268;
			
			// aapt resource value: 0x7f090016
			public const int button_login = 2131296278;
			
			// aapt resource value: 0x7f090029
			public const int button_play_and_pause = 2131296297;
			
			// aapt resource value: 0x7f090012
			public const int button_refresh = 2131296274;
			
			// aapt resource value: 0x7f09000d
			public const int button_send = 2131296269;
			
			// aapt resource value: 0x7f090028
			public const int button_skip_back = 2131296296;
			
			// aapt resource value: 0x7f09002a
			public const int button_skip_forward = 2131296298;
			
			// aapt resource value: 0x7f09001a
			public const int button_update = 2131296282;
			
			// aapt resource value: 0x7f09002b
			public const int controls_settings = 2131296299;
			
			// aapt resource value: 0x7f090024
			public const int image_preview = 2131296292;
			
			// aapt resource value: 0x7f090008
			public const int input_email = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int input_message = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int input_name = 2131296263;
			
			// aapt resource value: 0x7f090015
			public const int input_password = 2131296277;
			
			// aapt resource value: 0x7f090009
			public const int input_subject = 2131296265;
			
			// aapt resource value: 0x7f09001c
			public const int label_author = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int label_date = 2131296285;
			
			// aapt resource value: 0x7f09000f
			public const int label_last_updated = 2131296271;
			
			// aapt resource value: 0x7f090004
			public const int label_message = 2131296260;
			
			// aapt resource value: 0x7f09001e
			public const int label_text = 2131296286;
			
			// aapt resource value: 0x7f090018
			public const int label_title = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int label_version = 2131296281;
			
			// aapt resource value: 0x7f090020
			public const int layout_table = 2131296288;
			
			// aapt resource value: 0x7f09001f
			public const int list_attachments = 2131296287;
			
			// aapt resource value: 0x7f090013
			public const int list_feedback_messages = 2131296275;
			
			// aapt resource value: 0x7f090026
			public const int seekbar_position = 2131296294;
			
			// aapt resource value: 0x7f090022
			public const int seekbar_volume = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int table_row1 = 2131296289;
			
			// aapt resource value: 0x7f090023
			public const int table_row2 = 2131296291;
			
			// aapt resource value: 0x7f090025
			public const int table_row3 = 2131296293;
			
			// aapt resource value: 0x7f090027
			public const int table_row4 = 2131296295;
			
			// aapt resource value: 0x7f090014
			public const int text_headline = 2131296276;
			
			// aapt resource value: 0x7f090017
			public const int view_header = 2131296279;
			
			// aapt resource value: 0x7f09001b
			public const int web_update_details = 2131296283;
			
			// aapt resource value: 0x7f09000b
			public const int wrapper_attachments = 2131296267;
			
			// aapt resource value: 0x7f090006
			public const int wrapper_feedback = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int wrapper_feedback_scroll = 2131296261;
			
			// aapt resource value: 0x7f09000e
			public const int wrapper_messages = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int wrapper_messages_buttons = 2131296272;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hockeyapp_activity_expiry_info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hockeyapp_activity_feedback = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hockeyapp_activity_login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hockeyapp_fragment_update = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_view_feedback_message = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int controls_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05005a
			public const int about = 2131034202;
			
			// aapt resource value: 0x7f050057
			public const int app_name = 2131034199;
			
			// aapt resource value: 0x7f05006a
			public const int back = 2131034218;
			
			// aapt resource value: 0x7f05006d
			public const int forward = 2131034221;
			
			// aapt resource value: 0x7f050058
			public const int full_app_name = 2131034200;
			
			// aapt resource value: 0x7f050001
			public const int hockeyapp_crash_dialog_app_name_fallback = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int hockeyapp_crash_dialog_message = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int hockeyapp_crash_dialog_negative_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int hockeyapp_crash_dialog_neutral_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int hockeyapp_crash_dialog_positive_button = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int hockeyapp_crash_dialog_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int hockeyapp_dialog_error_message = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int hockeyapp_dialog_error_title = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int hockeyapp_dialog_positive_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int hockeyapp_download_failed_dialog_message = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int hockeyapp_download_failed_dialog_negative_button = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int hockeyapp_download_failed_dialog_positive_button = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int hockeyapp_download_failed_dialog_title = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int hockeyapp_error_install_form_unknown_sources_disabled = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int hockeyapp_error_no_external_storage_permission = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int hockeyapp_error_no_network_message = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int hockeyapp_expiry_info_text = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int hockeyapp_expiry_info_title = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int hockeyapp_feedback_attach_file = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int hockeyapp_feedback_attach_picture = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int hockeyapp_feedback_attachment_added = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int hockeyapp_feedback_attachment_button_text = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int hockeyapp_feedback_attachment_error = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int hockeyapp_feedback_attachment_loading = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int hockeyapp_feedback_attachment_remove_description = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int hockeyapp_feedback_attachment_removed = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int hockeyapp_feedback_email_hint = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int hockeyapp_feedback_email_hint_required = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int hockeyapp_feedback_fetching_feedback_text = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int hockeyapp_feedback_last_updated_text = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int hockeyapp_feedback_max_attachments_allowed = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int hockeyapp_feedback_message_hint = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int hockeyapp_feedback_message_hint_required = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int hockeyapp_feedback_name_hint = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int hockeyapp_feedback_name_hint_required = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int hockeyapp_feedback_new_answer_notification_message = 2131034148;
			
			// aapt resource value: 0x7f050055
			public const int hockeyapp_feedback_notification_channel = 2131034197;
			
			// aapt resource value: 0x7f050025
			public const int hockeyapp_feedback_notification_title = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int hockeyapp_feedback_refresh_button_text = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int hockeyapp_feedback_response_button_text = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int hockeyapp_feedback_screenshot_fail = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int hockeyapp_feedback_screenshot_notification_message = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int hockeyapp_feedback_select_file = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int hockeyapp_feedback_select_picture = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int hockeyapp_feedback_send_button_text = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int hockeyapp_feedback_send_generic_error = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int hockeyapp_feedback_send_network_error = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int hockeyapp_feedback_sending_feedback_text = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int hockeyapp_feedback_sent_toast = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int hockeyapp_feedback_subject_hint = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int hockeyapp_feedback_subject_hint_required = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int hockeyapp_feedback_title = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int hockeyapp_feedback_validate_email_empty = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int hockeyapp_feedback_validate_email_error = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int hockeyapp_feedback_validate_name_error = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int hockeyapp_feedback_validate_subject_error = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int hockeyapp_feedback_validate_text_error = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int hockeyapp_login_email_hint_required = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int hockeyapp_login_headline_text = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int hockeyapp_login_headline_text_email_only = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int hockeyapp_login_login_button_text = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int hockeyapp_login_missing_credentials_toast = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int hockeyapp_login_password_hint_required = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int hockeyapp_paint_dialog_message = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int hockeyapp_paint_dialog_negative_button = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int hockeyapp_paint_dialog_neutral_button = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int hockeyapp_paint_dialog_positive_button = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int hockeyapp_paint_indicator_toast = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int hockeyapp_paint_menu_clear = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int hockeyapp_paint_menu_save = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int hockeyapp_paint_menu_undo = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int hockeyapp_update_already_installed = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int hockeyapp_update_button = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int hockeyapp_update_dialog_message = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int hockeyapp_update_dialog_negative_button = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int hockeyapp_update_dialog_positive_button = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int hockeyapp_update_dialog_title = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int hockeyapp_update_loading = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int hockeyapp_update_mandatory_toast = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int hockeyapp_update_newest_version = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int hockeyapp_update_no_info = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int hockeyapp_update_restore = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int hockeyapp_update_title = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int hockeyapp_update_unknown_size = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int hockeyapp_update_version = 2131034196;
			
			// aapt resource value: 0x7f050056
			public const int hockeyapp_update_version_details_label = 2131034198;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f05006c
			public const int pause = 2131034220;
			
			// aapt resource value: 0x7f05006b
			public const int play = 2131034219;
			
			// aapt resource value: 0x7f050069
			public const int pref_about_title = 2131034217;
			
			// aapt resource value: 0x7f05005e
			public const int pref_category_connection_title = 2131034206;
			
			// aapt resource value: 0x7f050067
			public const int pref_category_information_title = 2131034215;
			
			// aapt resource value: 0x7f050062
			public const int pref_host_default_value = 2131034210;
			
			// aapt resource value: 0x7f050063
			public const int pref_host_dialog_title = 2131034211;
			
			// aapt resource value: 0x7f050061
			public const int pref_host_title = 2131034209;
			
			// aapt resource value: 0x7f050065
			public const int pref_port_default_value = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int pref_port_dialog_title = 2131034214;
			
			// aapt resource value: 0x7f050064
			public const int pref_port_title = 2131034212;
			
			// aapt resource value: 0x7f050060
			public const int pref_startup_summary = 2131034208;
			
			// aapt resource value: 0x7f05005f
			public const int pref_startup_title = 2131034207;
			
			// aapt resource value: 0x7f050068
			public const int pref_terms_title = 2131034216;
			
			// aapt resource value: 0x7f05005d
			public const int required_value = 2131034205;
			
			// aapt resource value: 0x7f05005c
			public const int rights = 2131034204;
			
			// aapt resource value: 0x7f050059
			public const int settings = 2131034201;
			
			// aapt resource value: 0x7f05005b
			public const int version = 2131034203;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int HockeyApp_ButtonStyle = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int HockeyApp_EditTextStyle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int HockeyApp_SingleLineInputStyle = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
